version: '3.8'
services:
  db:
    image: postgres:12.8
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  app:
    container_name: weather_api
    image: valeriia/weather_api
    build: ./
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  db:
