{
 "title": "Weather API Metrics",
 "panels": [
  {
   "title": "HTTP Requests Per Minute (excluding /metrics)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{endpoint!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Day (excluding /metrics)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{endpoint!=\"/metrics\"}[1d]))"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Subscriptions Created per 10 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(http_requests_total{endpoint=\"/api/subscribe\", status=\"200\",method=~\".*\"}[10m])"
    }
   ]
  },
  {
   "title": "Subscriptions Confirmed per 10 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(http_requests_total{endpoint=\"/api/confirm/:token\", status=\"200\",method=~\".*\"}[10m])"
    }
   ]
  },
  {
   "title": "Subscriptions Deleted per 10 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(http_requests_total{endpoint=\"/api/unsubscribe/:token\", status=\"200\",method=~\".*\"}[10m])"
    }
   ]
  },
  {
   "title": "Get weather per 10 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(http_requests_total{endpoint=\"/api/weather\", status=\"200\"}[10m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100"
    }
   ]
  }
 ]
}